// Generated by https://quicktype.io

export interface DataInterface {
    data?:       Datum[];
    status?:     number;
    statusText?: string;
    headers?:    DataInterfaceHeaders;
    config?:     Config;
    request?:    Request;
}

export interface Config {
    transitional:      Transitional;
    transformRequest:  null[];
    transformResponse: null[];
    timeout:           number;
    xsrfCookieName:    string;
    xsrfHeaderName:    string;
    maxContentLength:  number;
    maxBodyLength:     number;
    headers:           ConfigHeaders;
    method:            string;
    url:               string;
}

export interface ConfigHeaders {
    Accept: string;
}

export interface Transitional {
    silentJSONParsing:   boolean;
    forcedJSONParsing:   boolean;
    clarifyTimeoutError: boolean;
}

export interface Datum {
    average: number;
    end:     string;
    start:   string;
}

export interface DataInterfaceHeaders {
    "content-length": string;
    "content-type":   string;
}

export interface Request {
}
